# Generated by Django 6.0.2 on 2026-02-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='GHS', max_length=50),
        ),
    ]
