# Generated by Django 6.0.2 on 2026-02-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_order_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal_code',
            new_name='phone_number',
        ),
    ]
