# Generated by Django 6.0.2 on 2026-02-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_postal_code_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
